version: "3.7"
services:
  db:
    image: postgres
    hostname: demo-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    volumes:
      - ${DATA_PATH:-./tmp/postgress-demo-data}:/var/lib/postgresql/data
      